### ISSUE TITLE
Баг на Evolution 1.4.0.RC2

### ISSUE THREAD

**Issue by Typodin** [Aharito/DLSiblings#15]
При попытке запуска с дефолтными параметрами выдает 

Fatal error: Class 'APIhelpers' not found in ........./manager/includes/document.parser.class.inc.php(1832) : eval()'d code on line 45

**Comment by Aharito** [comment]
Сниппет был написан давно, для версии 7.1.6 (указано в коде, строка 8).

Добавьте после строки 31 такой код:

```
include_once(MODX_BASE_PATH . 'assets/lib/APIHelpers.class.php');
$DLDir = MODX_BASE_PATH . 'assets/snippets/DocLister/';
require_once($DLDir . "core/DocLister.abstract.php");
```

Отпишитесь о результатах, плиз.
