### ISSUE TITLE
Добавить отдельные шаблоны для "пред" и "след".

### ISSUE THREAD

**Issue by Kymage2010** [Aharito/DLSiblings#21]
Поскольку снипет универсальный, то для использования как замена prevnextPage нужно добавить разные шаблоны для Пред и След документ. Для магазинов такая фишка ни к чему, а вот для блоговых сайтов очень полезна. Сейчас шаблон вывода один, а заверстать два блока с отступами между ними и чтоб по центру нельзя одним правилом CSS.

**Comment by Aharito** [comment]
> заверстать два блока с отступами между ними и чтоб по центру нельзя одним правилом CSS.

Два блока - в одном только предыдущие, а в другом только последующие? вы это имеете в виду?

**Comment by Kymage2010** [comment]
Да, верно.

**Comment by Aharito** [comment]
Так как сниппет использует шаблонизацию Доклистер, то, как я написал в инструкции, можно использовать все шаблоны ДокЛистера. Поэтому я вижу сразу несколько решений:
1. Если блоков 2, то CSS-решение first-child и (или) last-child.
2. Если блоков 2, то не-CSS решение tplFirst и (или) tplLast.
3. Если блоков более 2-х, то не-CSS решение tpiId1, tplId2 и т.д.

Да и в принципе можно просто 2 раза вызвать сниппет. В общем, много решений.

**Comment by Kymage2010** [comment]
Точно! спасибо, про второй вариант совсем забыл, хоть не давно и использовал. Доклистер конечно гениален)
