### ISSUE TITLE
DL api parameter

### ISSUE THREAD

**Issue by 2frags** [Aharito/DLSiblings#22]
Snippet returns an array like `{ "5": [ ], "4": [ ], "3": [ ], "2": [ ], "1": [ ] }` on Evo 1.4.8.
I think i have found a wrong parameter in snippet.DLSiblings.php (44):
`$paramsAPI = array_merge( $params, array('api' => 'id', 'display' => '0') );`
I thought, DL have only 2 options for **api** parameter: 1 or 0.
So, changing **api** value from **id** to **1** fixed  the output.
It very strange, because another site on Evo 1.4.8 doesn`t have any issues with DLSiblings.
Has anybody seen similar issue before?
Thanks)

**Comment by Aharito** [comment]
В ранней версии DLSiblings я так и сделал. Параметр `&api` был установлен в значение `1`. Но при таком значении в JSON-массив попадают абсолютно все поля ресурса. Это на порядки увеличивает время обработки DocLister'ом и на выборках более 1000 нелинейно растет время работы сниппета.

Поэтому, во 2-й редакции сниппета я присвоил параметру `&api` значение `id`. Это дало приемлемые скорости на выборках 2-3 тысячи ресурсов.

***

In the early version of the DLSiblings, that was exactly the case. The `&api` parameter was set to `1`. But with this value, absolutely all resource fields fall into the JSON array. This increased the processing time by DocLister in the API mode tenfold. And on samples of more than 1000 resources, the snippet runtime nonlinearly increases.

Therefore, in the 2nd edition of the snippet, I assigned the `&api`value to `id`. This gave acceptable speeds on samples of 2-3 thousand resources.

***

Docs for DocLister http://docs.evo.im/04_extras/doclister/templates.html

![image](https://user-images.githubusercontent.com/6253807/57512635-63204c00-7336-11e9-9a6d-3917a751a2b9.png)

**Comment by Aharito** [comment]
> Snippet returns an array like { "5": [ ], "4": [ ], "3": [ ], "2": [ ], "1": [ ] } on Evo 1.4.8.

Возможно, на этом сайте у вас стоит старая версия DLSiblings. Обновите и сниппет, и его вызов.

Подробная документация [здесь](https://aharito.ru/modx-evolution/dlsiblings-podnimaem-sajt-po-nch-zaprosam), примеры [здесь](https://aharito.ru/modx-evolution/dlsiblings-primery-perelinkovki).

**Comment by 2frags** [comment]
Сегодня просто вернул значение  **api** к исходному - все работает.
Магия вобщем)
Спасибо!
________________________
Thank you!
I just have reverted **api** value to default one - **id**.
And everything working as expected..
